Henrique-Dias
Lucaszioli/Trabalho-Final-PDS2 pull request #35
Opened 2024-06-17 18:22 UTC by Henrique-Dias15

Retira opção de voltar ao trocar Monstrinhos quando um é desmaiado
Altera algumas mensagens

2024-06-17 19:37 UTC, nuvemnm approved these changes

2024-06-17 23:59 UTC, Lucaszioli requested changes

2024-06-17 23:59 UTC, Lucaszioli commented on CPPs/Jogador.cpp
>                  if (equipe[escolha - 1]->getHPAtual() <= 0)
Essa parte está gerando erro de segmentação, melhor fazer de outra maneira
![imagem_2024-06-17_164358538](https://github.com/Lucaszioli/Trabalho-Final-PDS2/assets/146764433/0c819f0e-cc20-4460-a74c-593cff5d6b42)

2024-06-18 00:29 UTC, Lucaszioli approved these changes
Certinho!!

2024-06-18 00:29 UTC, merged